### PR TITLE
Merge Application Layer into main

### LINKED ISSUE #2: Implement the Audio Database
# Description

This is where the audio data will be stored.

---

# Tasks

- [x] Add the ability to save audio files into the database

---

# Useful Links

[JMF link](https://www.oracle.com/java/technologies/javase/jmf-211-documentation.html)
[Stack Overflow on audio streaming](https://stackoverflow.com/questions/17044644/sending-audio-stream-over-tcp-unsupportedaudiofileexception)

### LINKED ISSUE #3: Implement the Basic Client for Streaming protocol

### LINKED ISSUE #4: Set up the streaming protocol

### PR DESCRIPTION
**Pull request by SOuellette22**

### CODE REVIEW

File: src/common/message/ByteMessage.java [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+    public void deserialize(JSONType jsonType) throws InvalidObjectException {
+        if (!(jsonType instanceof JSONObject)) {
+            throw new InvalidObjectException("JSONObject expected.");
+        }
+
+        JSONObject obj = (JSONObject) jsonType;
+
+        super.deserialize(obj);
+
+        obj.checkValidity(new String[]{"type", "data"});
```
Comment (SethMC26) [inline src/common/message/ByteMessage.java]: I beleve super class already checks for type

File: src/common/message/ByteMessage.java [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+    public ByteMessage(JSONObject jsonMessage) {
+        super(jsonMessage);
+        if (!super.type.equals("Byte")) {
+            throw new IllegalArgumentException("Bad type: " + super.type);
+        }
+    }
+
+    @Override
+    public void deserialize(JSONType jsonType) throws InvalidObjectException {
+        if (!(jsonType instanceof JSONObject)) {
```
Comment (SethMC26) [inline src/common/message/ByteMessage.java]: Super class already handles type check, I would move the super class first and avoid redundant checks made by super class. 
```java
 @Override
    public void deserialize(JSONType jsonType) throws InvalidObjectException {
       super.deserialize(jsonType)
       ....
```

File: src/common/message/Request.java [hunk 3]
```diff
@@ -0,0 +1,126 @@
...
+                super.type.equals("Add") || super.type.equals("Play") || super.type.equals("List"))) {
+            throw new IllegalArgumentException("Bad type: " + super.type);
+        }
+    }
+
+    @Override
+    public void deserialize(JSONType jsonType) throws InvalidObjectException {
+        if (!(jsonType instanceof JSONObject)) {
+            throw new InvalidObjectException("JSONObject expected.");
+        }
```
Comment (SethMC26) [inline src/common/message/Request.java]: See earlier comments

File: src/server/AudioDatabase.java [hunk 4]
```diff
@@ -0,0 +1,185 @@
...
+    @Override
+    public void deserialize(JSONType jsonType) throws InvalidObjectException {
+        if (!(jsonType instanceof JSONArray)) {
+            throw new InvalidObjectException("Audio JSON is not a JSONArray");
+        }
+
+        JSONArray array = (JSONArray) jsonType;
+
+        for (int i = 0; i < array.size(); i++) {
+            JSONType obj = (JSONObject) array.get(i);
```
Comment (SethMC26) [inline src/server/AudioDatabase.java]: Consider using array.getObject here, also you cast it before you do a type check, which could lead to undefined behavior

File: src/server/Server.java [hunk 5]
```diff
@@ -1,11 +1,179 @@
...
+
+            ServerSocket serverSocket = new ServerSocket(port);
+
+            while(true) {
+
+                MessageSocket socket = new MessageSocket(serverSocket.accept());
+
+                executor.execute(new ServerConnectionHandler(socket, audioDatabase, usersDatabase));
+            }
+        } catch (Exception e) {
```
Comment (SethMC26) [inline src/server/Server.java]: Thou shall not catch exception (SOCD)

**Review by SethMC26 — APPROVED** [review]
On testing it worked to play audio! Nicely done.

File: src/server/AudioDatabase.java [hunk 6]
```diff
@@ -131,7 +131,7 @@ public void deserialize(JSONType jsonType) throws InvalidObjectException {
         JSONArray array = (JSONArray) jsonType;
 
         for (int i = 0; i < array.size(); i++) {
-            JSONType obj = (JSONObject) array.get(i);
+            JSONType obj =  array.getObject(i);
             if (!(obj instanceof JSONObject)) {
```
Comment (SethMC26) [inline src/server/AudioDatabase.java]: We dont need this check since obj(.getObject always returns JSONObject) will always be a JSONObject, parser could also return null here in the case that type is not a JSONObject(argument to be made we should handle this case but we literally do not handle it anywhere else)
